const invert = require('lodash.invert');

const WINDOW_STATES = {
  UNKNOWN: 0,

  HAS_ACHIEVEMENT_MAP: 1,
  HAS_ACHIEVEMENT_LIST: 2,
  HAS_ACHIEVEMENT_BRIDGE: 3,

  HAS_GIFT: 10,

  ANDROID_HOMESCREEN: 20,

  TITLE_SCREEN: 41,
  UPDATED_DATA_AVAILABLE: 42, // needs pic
  UPDATE_SCREEN: 43,  // needs pic
  SESSION_EXPIRED: 44,

  BRIDGE: 50,
  BRIDGE_UPDATE_NEWS: 51,
  BRIDGE_DAILY_BOX: 52,
  BRIDGE_SUPPORT_MEDALS: 53,

  ACHIEVEMENTS_AVAIL: 61,
  ACHIEVEMENTS: 62,
  ACHIEVEMENTS_MODAL: 63,
  ACHIEVEMENTS_CAT_CLEAR: 64,

  GIFT_BOX: 71,
  GIFT_BOX_EMPTY: 72,
  GIFT_BOX_MODAL: 73,

  EVENT_SCREEN: 80,
  EVENT_SCREEN_MAP: 81,
  EVENT_SCREEN_MISSION: 82,
  EVENT_JOIN_ALL: 83,
  EVENT_SCREEN_STORY: 84,

  MISSION_START: 90,
  MISSION_START_MP: 91,
  MISSION_START_MP_MATCH: 92,
  MISSION_START_QUEUE: 93,
  MISSION_START_QUEUE_RETRY: 94,
  MISSION_START_PARTY: 95,
  MISSION_START_DISBAND: 96,
  MISSION_START_CHAR_DETAILS: 97,
  MISSION_START_DISCONNECT: 98,
  MISSION_START_PARTY_LEAVE: 99,
  MISSION_START_PARTY_LEFT: 100,
  MISSION_START_UNKNOWN_ERR: 101,
  MISSION_START_UNSTABLE_ERR: 102,

  COMBAT_START_RUSH_1: 120,
  COMBAT_START_RUSH_2: 121,
  COMBAT_START_RUSH_3: 122,
  COMBAT_START_RUSH_4: 123,
  COMBAT_DISCONNECT: 124,
  COMBAT_DISCONNECT_2: 125,
  COMBAT: 126,

  REWARD1: 130,
  REWARD2: 131,
  REWARD3: 132,

  STORY_SCREEN: 140
};

const WINDOW_NAMES = invert(WINDOW_STATES);

module.exports = {
  WINDOW_STATES,
  WINDOW_NAMES
};