
const { WINDOW_STATES } = require('./window.states');

const WINDOW_CLICKS = {

  // BRIDGE -> *
  [WINDOW_STATES.BRIDGE]: {
    [WINDOW_STATES.EVENT_SCREEN]: { x: 100, y: 830 },
    [WINDOW_STATES.GIFT_BOX]: { x: 500, y: 225 },
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 500, y: 315 }
  },

  // GIFT BOX -> *
  [WINDOW_STATES.GIFT_BOX]: {
    [WINDOW_STATES.GIFT_BOX_MODAL]: { x: 460, y: 850 }
  },
  [WINDOW_STATES.GIFT_BOX_MODAL]: {
    [WINDOW_STATES.GIFT_BOX]: { x: 280, y: 610 }
  },
  [WINDOW_STATES.GIFT_BOX_EMPTY]: {
    [WINDOW_STATES.BRIDGE]: { x: 100, y: 850 }
  },
  
  // EVENT SCREEN -> *
  [WINDOW_STATES.EVENT_SCREEN]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 480, y: 200 },
    [WINDOW_STATES.EVENT_JOIN_ALL]: { x: 400, y: 850 }
  },
  [WINDOW_STATES.EVENT_SCREEN_MISSION]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 480, y: 200 },
    [WINDOW_STATES.EVENT_JOIN_ALL]: { x: 400, y: 850 }
  },
  [WINDOW_STATES.EVENT_SCREEN_MAP]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 480, y: 300 },
    [WINDOW_STATES.EVENT_JOIN_ALL]: { x: 400, y: 850 },
  },
  [WINDOW_STATES.EVENT_JOIN_ALL]: {
    [WINDOW_STATES.MISSION_START_QUEUE]: { x: 375, y: 455 },
    [WINDOW_STATES.MISSION_START_MP_MATCH]: { x: 375, y: 455 }
  },

  // MISSION SCREEN -> *
  [WINDOW_STATES.MISSION_START]: {
    [WINDOW_STATES.MISSION_START_MP]: { x: 420, y: 690 }
  },
  [WINDOW_STATES.MISSION_START_MP]: {
    [WINDOW_STATES.MISSION_START_MP_MATCH]: { x: 330, y: 490 }
  },
  [WINDOW_STATES.MISSION_START_MP_MATCH]: {
    [WINDOW_STATES.MISSION_START_QUEUE]: { x: 425, y: 690 }
  },
  [WINDOW_STATES.MISSION_START_QUEUE_RETRY]: {
    [WINDOW_STATES.MISSION_START_QUEUE]: { x: 330, y: 520 }
  },

  // ACHIEVEMENT -> BOX
  [WINDOW_STATES.HAS_ACHIEVEMENT_BRIDGE]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 500, y: 315 }
  },
  [WINDOW_STATES.HAS_ACHIEVEMENT_LIST]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 500, y: 175 }
  },
  [WINDOW_STATES.HAS_ACHIEVEMENT_MAP]: {
    [WINDOW_STATES.ACHIEVEMENTS]: { x: 500, y: 270 }
  }
};

module.exports = {
  WINDOW_CLICKS
};